name: Build and test trees
on: push
jobs:
  build-and-run-test:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: action/setup-java@4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle Wrapper
        run: cd task4 && ./gradlew build